# Generated by Django 3.0.7 on 2020-07-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='mera_post',
            field=models.TextField(blank=True, null=True),
        ),
    ]
