# Generated by Django 3.0.7 on 2020-07-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('message_timings', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
