# Generated by Django 3.0.7 on 2020-07-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_forumpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
