# Generated by Django 3.0.7 on 2020-07-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_auto_20200722_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='message_timings',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
