# Generated by Django 3.0.7 on 2020-07-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_auto_20200724_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-updated', '-timestamp']},
        ),
        migrations.RenameField(
            model_name='forumpost',
            old_name='message_timings',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
