# Generated by Django 3.0.7 on 2020-08-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_forumpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
